### ISSUE TITLE
Suggest revising CW rule 3

### ISSUE THREAD

**Issue by bHimes** [StochasticAnalytics/mastodon_info#1]
## Current rule

3 - please wrap non-structural biology related posts with a content wrapper with a specific "subject" line

## Mastodon request

Iris Y. [points out the](https://fediscience.org/@irisvirus/109584468656293324) rule is a bit too cumbersome. I agree. I intended to suggest CW for non-science posts.

## Please comment with suggested revisions 

Something like:

We welcome non-science-related posts, but please consider using content wrappers if posting many in a short time period to help others filter their feed.

**Comment by irisdyoung** [comment]
I think my best suggestion is to soften the language and clarify the intent, e.g.:

3 - we strongly encourage the use of content wrappers (CWs) to tag posts that aren’t targeted at the entire community, especially long threads of non-science posts, to allow others to curate their feeds

Correct me if this is not your intent though!

**Comment by bHimes** [comment]
@irisdyoung  

Next iteration:

3 - we encourage you to be you. We also encourage (but don't require) the use of content wrappers (CWs) to tag posts that aren’t targeted at the entire community to allow others to curate their feeds. CW has a subject line and blurs the rest by default. This does not seem to limit engagement!

**Comment by irisdyoung** [comment]
Love it, endorse 100%
